### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rehti02** [bash0/cewe2pdf#186]
Hello,

I am trying to use this script but I am getting this error.
Is this an issue in the script or am I doing something wrong?

```
19:58:33 - root - ERROR - Exception
Traceback (most recent call last):
  File "C:\Program Files\Tools\cewe2pdf\cewe2pdf.py", line 1658, in convertMcf
    page = [i for i in
IndexError: list index out of range
19:58:33 - root - ERROR - error on page 0: list index out of range
19:58:33 - root - INFO - parsing page 1  of 3
19:58:39 - root - ERROR - Exception
Traceback (most recent call last):
  File "C:\Program Files\Tools\cewe2pdf\cewe2pdf.py", line 1658, in convertMcf
    page = [i for i in
IndexError: list index out of range
19:58:39 - root - ERROR - error on page 2: list index out of range
19:58:40 - root - INFO - GC collected objects : 0
Total message counts, including messages suppressed by logger configuration
cewe2pdf.config: ERROR[2], WARNING[86], INFO[949]
root:            ERROR[4], INFO[9]
```

**Comment by AnEnglishmanInNorway** [comment]
Difficult to say, without more information about the CEWE album file (mcf or mcfx) you are using. On line 1658 the script is looking for the cover page where pagenr="0", the type attribute is "fullcover" and there is some kind of content. Perhaps you have done something special with the cover that none of the other users have ever done. The script only really handles stuff that one or more of us has needed! I suppose one possibility is that you're creating photo project which is not an album, and so there is no cover page.

If you can't think of something particular that you have done, then you'll have to have a look at what the xml in the album file looks like. If you're using the latest mcfx format for the album, try "save as" and save it as an mcf project. Then you can read the mcf file in some text editor and have a look around the area where the cover is defined.
The unit test mcf file looks a like this in the area of the cover definition
```
    <page designStyleID="0" pagenr="0" rotation="0" type="fullcover">
        <bundlesize height="2750" width="4290"/>
        <designElementIDs background="201" layout="384109"/>
        <background alignment="4" designElementId="201" rotation="0" type="1"/>
        <background designElementId="384109" layout="1" templatename="full_page_fotobooks"/>
        <area areatype="imagearea">
            <position height="2950" left="-100" rotation="0" top="-100" width="2192" zposition="100"/>
            <decoration/>
            <image filename="safecontainer:/img6.png" useABK="0">
                <cutout left="-10.25" scale="4.60938" top="0"/>
                <quality noise="0" sharpness="0" texture="0"/>
            </image>
        </area>
```

**Comment by rehti02** [comment]
Thanks for the quick reply! That's going to be exactly the issue. If I find the time I will look into it a bit more and see if I can extend the functionality of the script to support this type of project.
But I think for the time being we can close this issue.

**Comment by AnEnglishmanInNorway** [comment]
I might reopen this and see if I can quickly make the code give a better error message than "index out of range". Something like "this is not recognisable as a fotobook project"!
